### PR TITLE
Add more detailed message when no library targets found.

### LINKED ISSUE #723: Improve error message when no library targets are found
### Discussed in https://github.com/obi1kenobi/cargo-semver-checks/discussions/722

<div type='discussions-op-text'>

<sup>Originally posted by **sajis997** March 29, 2024</sup>
usiing the following in the pipeline

    - name: Check semver
      uses: obi1kenobi/cargo-semver-checks-action@v2

I am getting the following error:

error: no crates with library targets selected, nothing to semver-check
Error: The process '/home/runner/.cargo/bin/cargo' failed with exit code 1</div>

### PR DESCRIPTION
**Pull request by jw013**
Resolves #723

### CODE REVIEW

**Comment by obi1kenobi** [comment]
Looks good! Might have to update a test or two though.

**Comment by jw013** [comment]
I updated the tests that check the output. I'm a little stumped about the remaining CI failures - I see mentions of rustdoc v29, though, so I assume that's unrelated?

**Comment by obi1kenobi** [comment]
Huh, a new rustdoc format version must have been released without me noticing... Curious 🤔

I'll fix that, thanks for bringing my attention to it!

**Review by obi1kenobi — APPROVED** [review]

**Comment by obi1kenobi** [comment]
Fixing the nightly build is blocked pending a new version of an upstream crate being published. But that's why it's a non-required step in our CI -- we can merge without it.

I've fixed the other step that was problematic, so this can merge.

Thanks again!

**Pull request merged**
