### PR TITLE
Cache generated rustdoc for registry baselines

### PR DESCRIPTION
**Pull request by thomaseizinger**
This implements the suggestion discussion in https://github.com/obi1kenobi/cargo-semver-checks/issues/214. It turned out surprisingly simple :)

### CODE REVIEW

**Comment by thomaseizinger** [comment]
I've tested it locally on the `rust-libp2p` repository. It works after a `cargo clean` and cleans up after itself. A subsequent run detects the cached file and reuses it which speeds up things a fair bit.

**Review by obi1kenobi — APPROVED** [review]

**Comment by obi1kenobi** [comment]
@thomaseizinger if I were to release 0.18 with this caching change soon, when would be the best time for you? I'd love to have you onboard to test it in "the real world" as soon as it comes out, in case something doesn't behave quite as well as we had hoped.

**Comment by thomaseizinger** [comment]
> @thomaseizinger if I were to release 0.18 with this caching change soon, when would be the best time for you? I'd love to have you onboard to test it in "the real world" as soon as it comes out, in case something doesn't behave quite as well as we had hoped.

We can test it as soon as there is a binary. Why don't we release `0.18.0-alpha` and we use that in our CI for a bit?

**Comment by thomaseizinger** [comment]
> > @thomaseizinger if I were to release 0.18 with this caching change soon, when would be the best time for you? I'd love to have you onboard to test it in "the real world" as soon as it comes out, in case something doesn't behave quite as well as we had hoped.
> 
> We can test it as soon as there is a binary. Why don't we release `0.18.0-alpha` and we use that in our CI for a bit?

I am gonna be on NZ timezone for the next two weeks. With a pre-release, I can adjust our CI to create a cache on master and use that on PR workflow runs and play around what happens when we nuke the cache etc.

**Comment by tonowak** [comment]
@obi1kenobi it would be good to first merge #340 before creating the alpha release, since it touched some of this PR's code.

**Pull request merged**
