### PR TITLE
use `insta` for witness tests

### PR DESCRIPTION
**Pull request by suaviloquence**
See also https://github.com/obi1kenobi/cargo-semver-checks/pull/933#discussion_r1765798462.

Replaces custom snapshot code with `insta` when testing witness generation for lints, which should have better contributor experience.

### CODE REVIEW

**Comment by suaviloquence** [comment]
It's still ron, so multiline strings will not be rendered super well.  We could use a different serializer like `yaml` if this becomes a problem, and it would be very easy to change.

**Comment by obi1kenobi** [comment]
`yaml` is an interesting idea. If you try it and think it looks good, do you mind switching this to it?

I suspect many of our witnesses will be multi-line once we get past the basic "item deleted" ones, and diffing multi-line strings represented with escape sequences is going to get really annoying quickly. We risk letting bugs slip just because it was hard to notice the snapshot changed in an undesirable way (e.g. bad indentation etc.)

**Comment by suaviloquence** [comment]
It looks like the yaml serializer that `insta` uses doesn't support multiline strings (even though yaml-the-langauge does...) https://github.com/mitsuhiko/insta/issues/372.  However `toml` handles multiline strings perfectly, my test code is below (i added extra lines to the witness hint)

```
---
source: src/query.rs
description: "Lint `function_missing` did not have the expected witness output.\nSee https://github.com/obi1kenobi/cargo-semver-checks/blob/main/CONTRIBUTING.md#testing-witnesses\nfor more information."
expression: "&actual_witnesses"
---
[["./test_crates/feature_flags_validation/"]]
filename = 'src/lib.rs'
begin_line = 4
hint = '''
line 1
line 2
feature_flags_validation::foo_becomes_gated(...);'''

[["./test_crates/feature_flags_validation/"]]
filename = 'src/lib.rs'
begin_line = 5
hint = '''
line 1
line 2
feature_flags_validation::bar_becomes_gated(...);'''

[["./test_crates/features_simple/"]]
filename = 'src/lib.rs'
begin_line = 2
hint = '''
line 1
line 2
features_simple::feature_dependent_function(...);'''

[["./test_crates/function_const_removed/"]]
filename = 'src/lib.rs'
begin_line = 5
hint = '''
line 1
line 2
function_const_removed::fn_removed(...);'''

[["./test_crates/function_feature_changed/"]]
filename = 'src/lib.rs'
begin_line = 2
hint = '''
line 1
line 2
function_feature_changed::moving_from_feature_A_to_feature_B(...);'''

[["./test_crates/function_missing/"]]
filename = 'src/lib.rs'
begin_line = 1
hint = '''
line 1
line 2
function_missing::will_be_removed_fn(...);'''

[["./test_crates/function_missing/"]]
filename = 'src/lib.rs'
begin_line = 4
hint = '''
line 1
line 2
function_missing::pub_use_removed_fn(...);'''
```

**Review by obi1kenobi — APPROVED** [review]
Awesome work! 🚀

**Pull request merged**
