### PR TITLE
feat: Object safe trait nightly test

### PR DESCRIPTION
**Pull request by devanbenz**
- Adds test_crate and output for `trait_no_longer_object_safe` lint
- This is a +nightly rustdoc feature currently so will remain open as a draft PR until the feature is moved in to stable

### CODE REVIEW

**Comment by obi1kenobi** [comment]
Reminder to self:
- Rust 1.77 is the first one to ship trait dyn-safety in rustdoc JSON.
- The test cases here were checked and valid on Rust 1.77 beta and 1.78 nightly circa 2024-02-11. They are extremely unlikely to drift.
- Merge this PR when Rust 1.77 is our lower bound.

**Comment by obi1kenobi** [comment]
@devanbenz if you don't mind, could you remove the lint file and macro invocation change, and add the trailing newlines to all the test files here?

**Comment by devanbenz** [comment]
Yep absolutely!

**Comment by obi1kenobi** [comment]
Looks good, thanks!

**Comment by devanbenz** [comment]
https://releases.rs/ - when will 1.77 be lower bound? I know as of right now its stable.

**Comment by obi1kenobi** [comment]
Right now I'm thinking probably in another 3-4 Rust releases or so (~4-6 months), unless there's a huge burst of breaking changes in rustdoc JSON formats in consecutive Rust releases that causes more maintenance burden.

Any particular reason you're asking?

I'm under the impression that only the test case is left outstanding, all the rest of the work is merged and the Rust community already benefits from the new lint if they use Rust 1.77+. Is that also how you see it? Just wanted to make sure I'm not making some incorrect starting assumption here.

**Comment by devanbenz** [comment]
> Right now I'm thinking probably in another 3-4 Rust releases or so (~4-6 months), unless there's a huge burst of breaking changes in rustdoc JSON formats in consecutive Rust releases that causes more maintenance burden.
> 
> Any particular reason you're asking?
> 
> I'm under the impression that only the test case is left outstanding, all the rest of the work is merged and the Rust community already benefits from the new lint if they use Rust 1.77+. Is that also how you see it? Just wanted to make sure I'm not making some incorrect starting assumption here.

Nope, no specific reason! I've been just doing some spring cleaning on my PRs and issues in GitHub 😆

**Comment by obi1kenobi** [comment]
Thanks for keeping an eye on this and checking in!

**Comment by obi1kenobi** [comment]
I just released v0.33.0 of cargo-semver-checks, and that's the last release that will support Rust older than 1.77. After the release, I also merged a PR to drop Rust versions prior to 1.77 from the test matrix.

That means this PR is finally ready to merge!

**Pull request merged**
