### PR TITLE
Add integration test snapshots

### PR DESCRIPTION
**Pull request by suaviloquence**
Adds functionality using `insta_cmd` to create snapshot tests using the `cargo-semver-checks` executable.  I added a `--bugreport` test as an example.

### CODE REVIEW

**Comment by suaviloquence** [comment]
CI is failing because it doesn't have `cargo` to run `cargo -V` :sweat_smile: We could add it to rustup or I could add a filter to redact this.

**Comment by obi1kenobi** [comment]
There's definitely a `cargo` on CI, this is from the logs earlier:
```
rustc 1.81.0-beta.8 (4a101b4b5 2024-08-31)
binary: rustc
commit-hash: 4a101b4b5db701edee2b705d1cc1c58c6058c43f
commit-date: 2024-08-31
host: x86_64-unknown-linux-gnu
release: 1.81.0-beta.8
LLVM version: 18.1.7
cargo 1.81.0-beta.8 (2dbb1af80 2024-08-20)
release: 1.81.0-beta.8
commit-hash: 2dbb1af80a29[144](https://github.com/obi1kenobi/cargo-semver-checks/actions/runs/10672016078/job/29578792793?pr=905#step:3:151)75ba76827a312e29cedfa6b2f
commit-date: 2024-08-20
```

Something weird is going on with how it's invoked, I suppose?

The code change looks great and I especially love the detailed module-level doc comment. Happy to merge as soon as CI passes.

**Comment by obi1kenobi** [comment]
I think you might have fixed it. You might just need to set the color=never env var or flag, and update the snapshot.

**Review by obi1kenobi — APPROVED** [review]

**Comment by obi1kenobi** [comment]
That breakage is due to #902, I'm going to disable those tests until we find a fix for the problem. It's not related to your PR.

**Pull request merged**
